name: "build-test"
on:
  push:
    branches:
      - net203
  pull_request:
    branches:
      - net203

jobs:
  test-backend:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [macos-latest, windows-latest]
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.github/nuget-packages
      GRADLE_USER_HOME: ${{ github.workspace }}/.github/gradle
    steps:
      - uses: actions/checkout@v2

      # Prepare
      - name: Gradle JVM Cache
        uses: actions/cache@v1.1.0
        with:
          path: build/gradle-jvm
          key: ${{ runner.os }}.gradle-jvm.${{ hashFiles('**/*.gradle') }}+${{ hashFiles('gradle*') }}
      - name: Gradle Wrapper Cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.GRADLE_USER_HOME }}/wrapper
          key: ${{ runner.os }}.gradle-wrapper.${{ hashFiles('gradle/**') }}
      - name: Gradle Cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.GRADLE_USER_HOME }}/caches/modules-2
          key: ${{ runner.os }}.gradle.${{ hashFiles('**/*.gradle') }}
      - name: Prepare
        working-directory: ./rider-fsharp
        run: ./gradlew prepare

      # Build and Test ReSharper.FSharp
      - name: NuGet Cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}.nuget.${{ hashFiles('src/dotnet/**/*.csproj') }}+${{ hashFiles('src/dotnet/**/*.props') }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: '3.1.101'
      - name: Test ReSharper.FSharp
        working-directory: ./ReSharper.FSharp
        run: dotnet test --logger:nunit --results-directory TestResults

      - name: Report test results
        uses: MirrorNG/nunit-reporter@v1.0.9
        if: always()
        with:
          path: ./ReSharper.FSharp/TestResults/*.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}

      # Finalize
      - name: Stop Gradle Daemon # to collect Gradle cache
        working-directory: ./rider-fsharp
        run: ./gradlew --stop
